name: Deploy GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build e Deploy para o Cloud Run
    runs-on: ubuntu-latest
    environment: projeto-bencorp

    env:
      IMAGE_NAME: southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/projeto-bencorp-repo/bencorp-api:latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Decodificar chave da Service Account (Base64)
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > ${HOME}/sa-key.json

      - name: Configurar Google Cloud SDK e Docker
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_B64 }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Autenticar Docker no Artifact Registry
        run: |
          gcloud auth activate-service-account --key-file=${HOME}/sa-key.json
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Construir imagem Docker
        run: docker build -t $IMAGE_NAME .

      - name: Enviar imagem para o Artifact Registry
        run: docker push $IMAGE_NAME

      - name: Fazer deploy no Cloud Run
        run: |
          gcloud run deploy bencorp-api \
            --image $IMAGE_NAME \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances ${{ secrets.GCP_CLOUDSQL_INSTANCE_NAME }} \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}
